### YamlMime:PythonClass
uid: azure.identity.CredentialUnavailableError
name: CredentialUnavailableError
fullName: azure.identity.CredentialUnavailableError
module: azure.identity
inheritances:
- azure.core.exceptions.ClientAuthenticationError
summary: The credential did not attempt to authenticate because required data or state
  is unavailable.
constructor:
  syntax: 'CredentialUnavailableError(message: object | None = None, response: _HttpResponseCommonAPI
    | None = None, **kwargs: Any)'
  parameters:
  - name: message
    defaultValue: None
  - name: response
    defaultValue: None
methods:
- uid: azure.identity.CredentialUnavailableError.add_note
  name: add_note
  summary: "Exception.add_note(note) \u2013\nadd a note to the exception"
  signature: add_note()
- uid: azure.identity.CredentialUnavailableError.raise_with_traceback
  name: raise_with_traceback
  summary: 'Raise the exception with the existing traceback.


    Deprecated since version 1.22.0: This method is deprecated as we don''t support
    Python 2 anymore. Use raise/from instead.'
  signature: raise_with_traceback() -> None
- uid: azure.identity.CredentialUnavailableError.with_traceback
  name: with_traceback
  summary: "Exception.with_traceback(tb) \u2013\nset self.__traceback__ to tb and\
    \ return self."
  signature: with_traceback()
attributes:
- uid: azure.identity.CredentialUnavailableError.args
  name: args
- uid: azure.identity.CredentialUnavailableError.continuation_token
  name: continuation_token
  signature: 'continuation_token: str | None'
- uid: azure.identity.CredentialUnavailableError.error
  name: error
  signature: 'error: ODataV4Format | None'
- uid: azure.identity.CredentialUnavailableError.exc_msg
  name: exc_msg
  signature: 'exc_msg: str'
- uid: azure.identity.CredentialUnavailableError.exc_traceback
  name: exc_traceback
  signature: 'exc_traceback: TracebackType | None'
- uid: azure.identity.CredentialUnavailableError.exc_type
  name: exc_type
  signature: 'exc_type: Type[Any] | None'
- uid: azure.identity.CredentialUnavailableError.exc_value
  name: exc_value
  signature: 'exc_value: BaseException | None'
- uid: azure.identity.CredentialUnavailableError.inner_exception
  name: inner_exception
  signature: 'inner_exception: BaseException | None'
- uid: azure.identity.CredentialUnavailableError.message
  name: message
  signature: 'message: str'
- uid: azure.identity.CredentialUnavailableError.model
  name: model
  signature: 'model: Any | None'
- uid: azure.identity.CredentialUnavailableError.reason
  name: reason
  signature: 'reason: str | None'
- uid: azure.identity.CredentialUnavailableError.response
  name: response
  signature: 'response: _HttpResponseCommonAPI | None'
- uid: azure.identity.CredentialUnavailableError.status_code
  name: status_code
  signature: 'status_code: int | None'
