### YamlMime:PythonClass
uid: azure.data.tables.TableTransactionError
name: TableTransactionError
fullName: azure.data.tables.TableTransactionError
module: azure.data.tables
inheritances:
- azure.core.exceptions.HttpResponseError
summary: There is a failure in the transaction operations.
constructor:
  syntax: TableTransactionError(**kwargs)
variables:
- description: 'If available, the index of the operation in the transaction that caused
    the error.

    Defaults to 0 in the case where an index was not provided, or the error applies
    across operations.'
  name: index
  types:
  - <xref:int>
- description: The error code.
  name: error_code
  types:
  - <xref:azure.data.tables.TableErrorCode>
- description: The error message.
  name: message
  types:
  - <xref:str>
- description: Any additional data for the error.
  name: additional_info
  types:
  - <xref:typing.Mapping>[<xref:str>, <xref:typing.Any>]
methods:
- uid: azure.data.tables.TableTransactionError.add_note
  name: add_note
  summary: "Exception.add_note(note) \u2013\nadd a note to the exception"
  signature: add_note()
- uid: azure.data.tables.TableTransactionError.raise_with_traceback
  name: raise_with_traceback
  summary: 'Raise the exception with the existing traceback.


    Deprecated since version 1.22.0: This method is deprecated as we don''t support
    Python 2 anymore. Use raise/from instead.'
  signature: raise_with_traceback() -> None
- uid: azure.data.tables.TableTransactionError.with_traceback
  name: with_traceback
  summary: "Exception.with_traceback(tb) \u2013\nset self.__traceback__ to tb and\
    \ return self."
  signature: with_traceback()
attributes:
- uid: azure.data.tables.TableTransactionError.args
  name: args
- uid: azure.data.tables.TableTransactionError.continuation_token
  name: continuation_token
  signature: 'continuation_token: str | None'
- uid: azure.data.tables.TableTransactionError.error
  name: error
  signature: 'error: ODataV4Format | None'
- uid: azure.data.tables.TableTransactionError.exc_msg
  name: exc_msg
  signature: 'exc_msg: str'
- uid: azure.data.tables.TableTransactionError.exc_traceback
  name: exc_traceback
  signature: 'exc_traceback: TracebackType | None'
- uid: azure.data.tables.TableTransactionError.exc_type
  name: exc_type
  signature: 'exc_type: Type[Any] | None'
- uid: azure.data.tables.TableTransactionError.exc_value
  name: exc_value
  signature: 'exc_value: BaseException | None'
- uid: azure.data.tables.TableTransactionError.inner_exception
  name: inner_exception
  signature: 'inner_exception: BaseException | None'
- uid: azure.data.tables.TableTransactionError.message
  name: message
  signature: 'message: str'
- uid: azure.data.tables.TableTransactionError.model
  name: model
  signature: 'model: Any | None'
- uid: azure.data.tables.TableTransactionError.reason
  name: reason
  signature: 'reason: str | None'
- uid: azure.data.tables.TableTransactionError.response
  name: response
  signature: 'response: _HttpResponseCommonAPI | None'
- uid: azure.data.tables.TableTransactionError.status_code
  name: status_code
  signature: 'status_code: int | None'
